### ISSUE TITLE
error

### ISSUE THREAD

**Issue by ghost** [lattenwald/rust-tdlib#2]
thread 'main' panicked at 'index out of bounds: the len is 1 but the index is 1', /rustc/70f130954d6fd36fe3e77f4b5b33e5af50489288/src/libcore/slice/mod.rs:2686:10
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:39
   1: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at src/libstd/sys_common/backtrace.rs:59
             at src/libstd/panicking.rs:197
   3: std::panicking::default_hook
             at src/libstd/panicking.rs:211
   4: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:474
   5: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:381
   6: rust_begin_unwind
             at src/libstd/panicking.rs:308
   7: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
   8: core::panicking::panic_bounds_check
             at src/libcore/panicking.rs:61
   9: <usize as core::slice::SliceIndex<[T]>>::index
             at /rustc/70f130954d6fd36fe3e77f4b5b33e5af50489288/src/libcore/slice/mod.rs:2686
  10: core::slice::<impl core::ops::index::Index<I> for [T]>::index
             at /rustc/70f130954d6fd36fe3e77f4b5b33e5af50489288/src/libcore/slice/mod.rs:2543
  11: <alloc::vec::Vec<T> as core::ops::index::Index<I>>::index
             at /rustc/70f130954d6fd36fe3e77f4b5b33e5af50489288/src/liballoc/vec.rs:1677
  12: new::main
             at src/main.rs:15
  13: std::rt::lang_start::{{closure}}
             at /rustc/70f130954d6fd36fe3e77f4b5b33e5af50489288/src/libstd/rt.rs:64
  14: std::panicking::try::do_call
             at src/libstd/rt.rs:49
             at src/libstd/panicking.rs:293
  15: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:85
  16: std::rt::lang_start_internal
             at src/libstd/panicking.rs:272
             at src/libstd/panic.rs:388
             at src/libstd/rt.rs:48
  17: std::rt::lang_start
             at /rustc/70f130954d6fd36fe3e77f4b5b33e5af50489288/src/libstd/rt.rs:64
  18: main
  19: __libc_start_main
  20: _start

Process finished with exit code 101

**Comment by lattenwald** [comment]
Did you run an example program from `README`? It requires two arguments: app_id and app_hash, see how to run it at the bottom:

    $ cargo run <app_id> <app_hash>

You get app_id and app_hash at https://my.telegram.org/apps.

Please comment if I am wrong.

**Comment by ghost** [comment]
Sorry for my mistake, but he still doesn't work after running the command. The error is as follows.

$ cargo run <app_id> <app_hash>

[ 3][t 4][1555588813.733331919][Td.cpp:4289][!Td][&td_requests]	Sending update: updateAuthorizationState {
  authorization_state = authorizationStateWaitTdlibParameters {
  }
}

[ 3][t 4][1555588813.734378576][Td.cpp:4289][!Td][&td_requests]	Sending update: updateAuthorizationState {
  authorization_state = authorizationStateWaitEncryptionKey {
    is_encrypted = false
  }
}

[ 3][t 4][1555588813.734480381][Td.cpp:4298][!Td][&td_requests]	Sending result for request 1: ok {
}

**Comment by lattenwald** [comment]
This shows that Rust bindings works. This library is just Rust bindings to https://github.com/tdlib/td. Building client logic (like authorization, sending/receiving messages, etc.) is a separate task which is not done in this repository. This library allows you to use [JSON interface](https://core.telegram.org/tdlib/docs/td__json__client_8h.html) to [Telegram API](https://core.telegram.org/tdlib/docs/index.html).

I successfully used it to build a telegram client in [Erlang](https://github.com/lattenwald/erl-tdlib), there's some client logic implemented there, if you can read Erlang.

I am closing this issue, as everything works as it should.
